[project]
name = "build-a-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.7",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "safetensors>=0.8.0",
    "tiktoken>=0.13.0",
    "torch>=2.12.0",
]
